name: Test and Analyze

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/ODINwhiteboard/odin/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Grant execute permission to gradlew
        run: |
          cd ODINwhiteboard
          cd odin
          chmod +x ./gradlew


      - name: Build with Gradle
        run: |
          cd ODINwhiteboard
          cd odin
          ./gradlew build --warning-mode all

      - name: Run tests with Gradle
        run: |
          cd ODINwhiteboard
          cd odin
          ./gradlew test

  analyze:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Super-Linter Installation
        uses: github/super-linter@v5.0.0
        env:
            VALIDATE_ALL_CODEBASE: false
            DEFAULT_BRANCH: master
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}